### PR TITLE
scala 3.0.2

### PR DESCRIPTION
**Pull request by pjfanning**
Just upgrading to scala 3.0.2 due to https://twitter.com/SethTisue/status/1450260785762947076

This does run into an issue with sbt gitflow plugin - leading to this warning:

```
>>> Unknown gitflow branch: scala-3.0.2
```

### CODE REVIEW

**Comment by gzoller** [comment]
Gitflow is a little finicky and I’ve got my ci/cd wired to it.  I’ll pull this in.  I think there’s even a newer Scala 3 that moved some internal bits a little so I may upgrade to that.

**Comment by pjfanning** [comment]
@gzoller thanks for getting back - I had a mistake in description and I corrected it just now. The reason I suggest Scala 3.0.2 is because jars built with it work on Scala 3.1 too but Scala 3.1 built jars won't work on Scala 3.0.x.

**Comment by gzoller** [comment]
Interesting, OK, then maybe I'll do 2 releases.  One for 3.0.2 and one for 3.1.0.  I want to clean up deprecated stuff in 3.1.0 before they cut it out.  With hubflow, you can't just do a PR into master, or a plain PR for that matter.  You need "git hf feature start foo" off develop branch.  That's the start of the workflow.

**Comment by gzoller** [comment]
handled in next release.

**Pull request closed without merging**
