### PR TITLE
try to support java8 format classes

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by gzoller** [comment]
Question... Will this change produce a Java 8 jar artifact when published to maven?  If so, I don't think this is a good idea.  If it produces a Java 13 binary that is compatible with Java 8 format, that's ok.  I know Java 8 has been Scala's build standard since the stone age, but frankly its very old and very out-of-date in terms of security patches.  Many large companies won't even let you run it.  Scala 3 opened the door to newer jvms.  (13 isn't exactly new either...).   What is driving this request?

**Comment by pjfanning** [comment]
This change means you can build with newer versions of the Java runtime but the jar that gets produced will use java 8 compatible format.
I would encourage devs to use the latest Java runtimes but libraries generally try to support many java versions instead of limiting support to users with the latest JVMs. All major security patches are still being applied to Java 8. You can check its release history.

Have a look at the Java and Scala ecosystems, almost all jars that are published support Java 8 format. The Scala compiler (and Dotty compiler) supports Java 8 format for very similar reasons. A few support a minimum of Java 11 format but usually only when the jar relies on features that are only available in Java 11.

**Comment by gzoller** [comment]
1.1.1 is released with the requested changes made for jdk8.  Closing this, but if the jdk8 support doesn't work, please open an issue.

**Comment by pjfanning** [comment]
Thanks @gzoller - the 1.1.1 release works well

**Pull request closed without merging**
